services:
    roundcubemail:
        #    image: roundcube/roundcubemail:latest-frankenphp
        container_name: roundcubemail
        build:
            context: ../frankenphp/
            dockerfile: Dockerfile
        ports:
            - "9008:80"
        depends_on:
            - roundcubedb
        links:
            - roundcubedb
        volumes:
            - ./www:/app
        environment:
            - SERVER_NAME=:9008
            - ROUNDCUBEMAIL_DB_TYPE=pgsql
            - ROUNDCUBEMAIL_DB_HOST=roundcubedb # same as pgsql container name
            - ROUNDCUBEMAIL_DB_NAME=roundcube # same as pgsql POSTGRES_DB env name
            - ROUNDCUBEMAIL_DB_USER=roundcube # same as pgsql POSTGRES_USER env name
            - ROUNDCUBEMAIL_DB_PASSWORD=roundcube # same as pgsql POSTGRES_PASSWORD env name
            - ROUNDCUBEMAIL_SKIN=elastic
            - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.hm.emp.br
            - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.hm.emp.br

    roundcubedb:
        image: postgres:alpine
        container_name: roundcubedb
        # restart: unless-stopped
        volumes:
            - ./db/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=roundcube
            - POSTGRES_USER=roundcube
            - POSTGRES_PASSWORD=roundcube

### Optional: add a full mail server stack to use with Roundcube like https://hub.docker.com/r/tvial/docker-mailserver
#   mailserver:
#     image: tvial/docker-mailserver:latest
#     hostname: mail.example.org
#     ...  # for more options see https://github.com/tomav/docker-mailserver#examples
