name: 'Notify manually requested reminders'

on:
  schedule:
    - cron: '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  reminder:
    if: github.repository == 'roundcube/roundcubemail-docker'
    runs-on: ubuntu-latest

    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@ab1f38534c17a1c16ba96eaf5fb9c0015d509301 # v1.0.22
