name: Build & Publish nightly

permissions:
  contents: read

on:
  schedule:
    # Rebuild automatically each night
    - cron: "4 2 * * *"
  workflow_dispatch:

jobs:
  build-and-testvariants:
    name: Build image and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Docker
        # This step is required to enable the containerd image store, which is required by the cache type=gha
        uses: docker/setup-docker-action@77e84dbf09b47d1e29270283c22f16145aa85ca1 # v5.4.0
        with:
          daemon-config: |
           {
             "debug": true,
             "features": {
               "containerd-snapshotter": true
             }
           }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          buildkitd-flags: --debug

      - name: Build and test nightly image
        run: ./nightly/build-and-test.sh

      # Only log into docker now, so we benefit from the automatic caching of upstream images.
      - name: Get docker hub username
        id: creds
        run: echo 'username=${{ secrets.DOCKER_PULL_USERNAME }}' >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        if: steps.creds.outputs.username != ''
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_PULL_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_PASSWORD }}

      - name: Build and push nightly images for all platforms
        run: ./nightly/build-and-push.sh
