name: Build & Publish
permissions:
  contents: read
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
      - 'examples/**'
      - 'development/**'
      - 'nightly/**'
    tags:
      - '1.7.*'
      - '1.6.*'
  schedule:
    # Rebuild images each monday early morning to ensure a fresh base OS.
    - cron: "23 2 * * 1"
  workflow_dispatch:
jobs:
  build-and-testvariants:
    name: Build, test and push all image variants
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        variant: [apache, fpm, fpm-alpine]
        version: [1.7.1, 1.6.16]
        target: [root, nonroot]
        include:
          - version: 1.7.1
            tag_as_latest_arg: "--tag-as-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Docker
        # This step is required to enable the containerd image store, which is required by the cache type=gha
        uses: docker/setup-docker-action@0234bb73ccb40f0c430b795634f9247e2b5c2d23 # v5.2.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          buildkitd-flags: --debug
      - name: Build and test "${{ matrix.version }}" "${{ matrix.variant }} "${{ matrix.target }}"
        run: |
          ./build-image.sh --variant "${{ matrix.variant }}" --version "${{ matrix.version }}" --target "${{ matrix.target }}" --run-tests
      # Only log into docker now, so we benefit from the automatic caching of upstream images. (Apparently we
      # can only benefit from cached upstream images if the job is not authenticated.)
      - name: Get docker hub username
        id: creds
        run: echo 'username=${{ secrets.DOCKER_PULL_USERNAME }}' >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        if: steps.creds.outputs.username != ''
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_PULL_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_PASSWORD }}
      - name: Build and push "${{ matrix.version }}" "${{ matrix.variant }} "${{ matrix.target }}"
        run: |
          ./build-image.sh --variant "${{ matrix.variant }}" --version "${{ matrix.version }}" --target "${{ matrix.target }}" ${{ matrix.tag_as_latest_arg }} --platform "linux/arm64,linux/arm/v6,linux/arm/v7,linux/386,linux/amd64" --push
