name: Build & publish development image

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    paths:
      - 'development/**'
      - .github/workflows/*-development.yml
  schedule:
    # Rebuild images each monday morning to ensure a fresh base OS (but later than the main image building workflow,
    # because the development image builds on one of them)
    - cron: "23 4 * * 1"
  workflow_dispatch:

jobs:
  build_test_publish:
    name: Build, test and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Docker
        # This step is required to enable the containerd image store, which is required by the cache type=gha
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0
        with:
          daemon-config: |
           {
             "debug": true,
             "features": {
               "containerd-snapshotter": true
             }
           }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          buildkitd-flags: --debug

      - name: Build development image for tests"
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: development
          load: true
          tags: roundcube/roundcubemail:development
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test built image
        env:
          ROUNDCUBEMAIL_TEST_IMAGE: roundcube/roundcubemail:development
        run: ./development/test.sh

      # Only log into docker now, so we benefit from the automatic caching of upstream images.
      - name: Get docker hub username
        id: creds
        run: echo 'username=${{ secrets.DOCKER_PULL_USERNAME }}' >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        if: steps.creds.outputs.username != ''
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKER_PULL_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_PASSWORD }}

      - name: Build and push development images for all platforms
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: development
          platforms: "linux/arm64,linux/arm/v6,linux/arm/v7,linux/386,linux/amd64"
          push: true
          tags: roundcube/roundcubemail:development
          cache-from: type=gha
          cache-to: type=gha,mode=max
