name: Build & test development image

permissions:
  contents: read

on:
  pull_request:
      paths:
          - "development/**"
          - ".github/workflows/*-development.yml"

jobs:
  build-and-test:
    name: Build and test development image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          buildkitd-flags: --debug

      - name: Build and test development image
        run: ./development/build-and-test.sh
