name: Build & Test
permissions:
  contents: read
on:
  pull_request:
    paths-ignore:
      - "development/**"
      - .github/workflows/*-development.yml
      - "nightly/**"
      - "examples/**"
      - "README.md"
jobs:
  build-and-testvariants:
    name: Build image variants and run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        variant: [apache, fpm, fpm-alpine]
        version: [1.7.1, 1.6.16]
        target: [root, nonroot]
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Docker
        # This step is required to enable the containerd image store, which is required by the cache type=gha
        uses: docker/setup-docker-action@0234bb73ccb40f0c430b795634f9247e2b5c2d23 # v5.2.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Build and test "${{ matrix.version }}" "${{ matrix.variant }} "${{ matrix.target }}"
        run: |
          ./build-image.sh --variant "${{ matrix.variant }}" --version "${{ matrix.version }}" --target "${{ matrix.target }}" --run-tests
