name: Build & test development image

permissions:
  contents: read

on:
  pull_request:
      paths:
          - "development/**"
          - ".github/workflows/*-development.yml"

jobs:
  build-and-test:
    name: Build and test development image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build development image for tests"
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: development
          load: true
          tags: roundcube/roundcubemail:development

      - name: Test built image
        env:
          ROUNDCUBEMAIL_TEST_IMAGE: roundcube/roundcubemail:development
        run: ./development/test.sh
