name: Build & test development image

permissions:
  contents: read

on:
  pull_request:
      paths:
          - "development/**"
          - ".github/workflows/*-development.yml"

jobs:
  build-and-test:
    name: Build and test development image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build development image for tests"
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: development
          load: true
          tags: roundcube/roundcubemail:development

      - name: Test built image
        env:
          ROUNDCUBEMAIL_TEST_IMAGE: roundcube/roundcubemail:development
        run: ./development/test.sh
