name: update.sh

permissions:
  # Git push permissions are needed
  contents: write

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '11 0 * * *'
  workflow_dispatch:

jobs:
  run_update_sh:
    name: Run update.sh script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WOKFLOW_TOKEN }}
    - name: Run update.sh script
      run: ./update.sh
    - name: Commit files
      run: |
        git config --local user.email "workflow@github.com"
        git config --local user.name "GitHub Workflow"
        git add -A
        git commit -m "Update roundcube version (via update.sh)" || echo "Nothing to update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.WOKFLOW_TOKEN }}
